### ISSUE TITLE
RESTful GEVER API

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1282]
Es soll eine RESTful HTTP API für GEVER implentiert werden.

An der Kickoff-Sitzung vom 30.10. wurde beschlossen, diese soweit als möglich als eine API zu implementieren, die 4teamwork-weit für Plone-Projekte genutzt werden kann, auf Basis von `plone.rest` und `plone.restapi`.
### Primäre Use-Cases aus Sicht von GEVER
- GEVER AI (NEST)
  - Bestimmen ob ein Dossier mit einer PersID bereits existiert (Structured query / list folder contents)
  - Dossier erstellen
  - Datei als GEVER Dokument in Dossier erstellen
  - Kurz-URL auf Dossier/Dokument zurückgeben (Unique ID + Resolve view)
- CRUD
- Authentisierung

Noch offene Punkte:
- [x] Dokumentation auf docs.onegovgever.ch nachführen
- [x] View von Management von JWT Tokens
- [x] CSRF-Protection für `@login` endpoint deaktivieren

**Comment by lukasgraf** [comment]
This has been implemented.

Upstream resources:

- [`plone.rest`](https://github.com/plone/plone.rest) (enables the use of HTTP Verbs other than GET or POST in Plone, Support for CORS policies, and RESTful error handling)
- [`plone.restapi`](https://github.com/plone/plone.restapi/) (implementation of RESTful endpoints for stock Plone)
- [`plone.restapi` documentation](http://plonerestapi.readthedocs.io/en/latest/)

GEVER resources:

- Implementation of additional functionality / endpoints mostly in [`opengever.api`](https://github.com/4teamwork/opengever.core/tree/master/opengever/api)
- [German Documentation for GEVER API](https://docs.onegovgever.ch/dev-manual/api/)
- [`ftw.tokenauth`](https://github.com/4teamwork/ftw.tokenauth) (PAS Plugin for Machine-to-machine authentication using service keys and OAuth2)
- [German documentation for `ftw.tokenauth`](https://docs.onegovgever.ch/dev-manual/api/authentication/oauth2_token_auth/)
