### ISSUE TITLE
Clean up our translations and come up with a workflow

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1783]
We're currently evaluating [Weblate](https://weblate.org/) in order to maybe simplify our translation story.

However, regardless of what tools we'll be using, we need to clean up some aspects of our translations:

**Technical**
- [ ] Consistent use of either message IDs (`"button_save"`) or source strings (`"Save"`) as `msgids`.
  
    We currently have a [mix of both](https://github.com/4teamwork/opengever.core/blob/14af37a300d6aca45b9943fa8081635f65e50887/opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po#L204-L209). In the case of Weblate, they [support both](http://weblate.readthedocs.io/en/latest/formats.html#monolingual-gettext), but it needs to be configured on a per po-file basis, so at least inside a single `.po` file it should be consistent.
- [x] Remove empty `help_` texts (field descriptions)
- [ ] Change `bin/i18n-build` to not touch `.po[t]` files where the only change would be the updated timestamp (makes for much easier diffs)

**Workflow**
- [ ] We need a mechanism to lock translations in git. Weblate supports locking translations (on a per-project or per-component basis) for **translators**, but we would also need to lock translations for **developers** in git (pre-commit hook, extend `bin/i18n-build`, CI check?)
- [ ] Depending on whether we'll be using message IDs or source strings (see above), this has implications as to when translations will be marked fuzzy. So we need guidelines for developers for when they need to
  - manually mark translations as fuzzy
  - manually remove fuzzy markers in order not to burden translators
  - change the message ID because a source string changed its meaning

/cc @phgross @deiferni

**Comment by lukasgraf** [comment]
Closing for now since the current workflow works quite well, even though we haven't quite addressed all those issues. Might be reopened.
