### ISSUE TITLE
Erweiterung SPV mit Word-Protokollierung

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2829]
## Ziel:
- Anträge werden neu direkt in Word geschrieben.
- Die Sitzung wird neu in Word protokolliert.

## Konzeptionelle Änderungen:
- Der Antragstext im Antragsdossier wird nicht mehr mit dem Text in der Sitzung synchronisiert; neu wird der Text kopiert.
- Der Inhalt der Anträge wird nicht mehr schematisch Erfasst; das System kann die einzelnen Teile nicht mehr automatisch verarbeiten.

## Abgrenzungen:
- Der Migrationspfad für bestehende Inhalte wird noch nicht implementiert.

## Strategie technisch:
- Feature Flag “is_word_meeting_enabled” verwenden
- Bestehende FTIs werden erweitert und mit Feature-Flag-Conditions ergänzt

## Business Test Cases:
- Einreichen von Anträgen
- Zurückweisen von Anträgen
- Aktualisieren von Anträgen
- Traktandieren der Anträge für die Sitzung
- Erstellen eines Sitzungsprotokolls der Anträgen
- Rückmeldung des Beschlusses als Protokollauszug ins Ursprungsdossier
- Automatische Aktualisierung des Journals

## Implementation:
- [x] **Feature Flag “is_word_meeting_feature_enabled” erstellen** => #2832
- [x] **Neue FTI "ProposalTemplate"** => #2834
  - Felder “Titel” und “Datei” (Word), beides required
  - werden unter /vorlagen erstellt
- [x] **Neues Tab “Antragsvorlagen” im Vorlageordner** => #2835
- [x] **“Proposal” und “SubmittedProposal” erweitern**
  - ~~Neues Datei-Feld “Antrag”~~
  - ~~Bumblebee-Integration sicherstellen~~
  - [x] Opengever Dokument addable machen => #2879
  - [x] Referenz / Kenntniss des Antragsdokuments vom Antrag aus => #2879
  - [x] Sicherstellen, dass das Antragsdokument nicht in den Papierkorb verschoben wird => #2879
  - [x] Sicherstellen, dass das Antragsdokument nicht verschoben werden kann => #2879
  - [x] Auflistungen Anträge filterbar (Aktiv | Beschlossen) => #3366
  - [x] Auflistung Anträge Beschlussnummern darstellen => #3370
- [x] **Formular “Antrag erstellen”**
  - [x] Neues Feld “Antragsvorlage” => #2879
  - [x] Neue Checkbox “Nach dem Hinzufügen bearbeiten” => #3148
  - [x] Bestehende Textfelder mehrheitlich ausblenden => #2879
  - [x] Antragsvorlage bei Speichern in neuen Antrag kopieren => #2879
- [x] **Einreichen des Antrags**
  - [x] Sicherstellen, dass die Antragsdatei kopiert wird => #2879
  - [x] “Proposal” für Bearbeitung sperren (Workflow) => #2879
- [x] **Traktandieren des Antrags**
  - [x] Beim Traktandieren eines Antrags soll das Antragsdokument zum Beschlussdokument kopiert werden.
    - :question: Wollen wir wirklich kopieren?
      - Vorteil: Wenn der Antrag traktandiert wird (und zum Beschlussdokument umgeschrieben), dann aber wieder de-traktandiert wird, müssten wir den Stand "Antragsdokument" wiederherstellen; dies ist bei zwei separaten Dokumenten einfach.
      - Nachteil: Wir haben noch ein Dokument mehr (das sichtbar ist)
      - Variante: Kopieren und Antragsdokument in Papierkorb verschieben.
    - [x] Text "Antragsdokument" in Dokumenttitel soll neu "Beschlussdokument" sein.
    - [x] Auf Antrag-Ansicht soll das Label in der Tabelle von "Antragsdokument" zu "Beschlussdokument" ändern.
    - These: es könnte ausreichen, wenn im eingereichten Antrag das Antragsdokument lediglich als frühere Version im Beschlussdokument vorhanden ist; das heisst man müsste keine Kopie Antragsdokument => Beschlussdokument machen.
- [x] **Traktendenliste in Sitzung**
  - [x] Direkter Checkout (Office Connector) der Traktanden-Dokumente (ohne Weiterleitung auf Dokument) => #3194
  - [x] Antragsdokument resp. Beschlussdokument direkt anzeigen.
  - [x] Allgemein: Darstellung in Traktandenliste anpassen => #3155
  - [x] Darstellung korrigieren wenn Sitzung durchgeführt.
- [x] **Protokollierung**
  - Protokolliert wird in den einzelnen Antragsdokumenten in der Sitzung, die Änderungen werden nicht automatisch in das Antragsdossier zurückgespielt.
  - [x] Office-Connector Checkout direkt von Sitzungs-Übersicht, ohne Redirect auf die Dokumente (!) => der User soll immer auf der Sitzungs-Übersicht bleiben. => #3194
    - [x] Dokument wird automatisch für den Protokollführer ausgecheckt. => #3194
    - [x] Markieren ob Dokument ausgecheckt ist (Icon?). => #3194
- [x] **Sitzungsabschluss**
  - [x] Beschliessen des Traktandums: Beschlussdokument wird automatisch eingecheckt. => #3245
  - [x] Erstellen des Gesamtprotokolls durch Mergen aller protokollierten ~~Antrags~~Beschlussdokumente  => #3247
    - [x] Ablage im Sitzungsdossier
    - [x] Ab wann ist das Gesamtprotokoll bearbeitbar immer/erst nach Sitzungsabschluss?
    - :question: Muss noch genauer spezifiziert werden.
  - [x] Protokollauszug generieren
    - ~~neue Aktion, sichtbar als Button an gleicher Position bevor “Abschliessen” sichtbar ist~~
    - Neue Aktion "Protokollauszug generieren" pro Traktandum
      - [x] Aktion erst _nach_ Beschluss verfügbar => #3245
      - [x] ~~Aktionen u.U. umbauen zu einem Menu, mit beschrifteten Aktionen~~ _nicht der geeignete Zeitpunkt: dies sollte in einem UI/UX-Konzept allgemein angegangen werden_
      - [x] kopiert das Beschlussdokument => #3245
      - [x] protokollauszug wird im Sitzungsdossier abgelegt => #3245
        - es wird davon ausgegangen dass das Sitzungsdossier genügend restriktive Sichtbarkeitseinstellungen hat; es enthält ja auch das gesamtprotokoll
        - das Sitzungsdossier ist ein besserer Speicherort als der eingereichte Antrag, weil das Dossier Funktionen wie Aufgaben bereits anbietet
        - der Protokollführer muss die Möglichkeit haben, das Dokument zuerst zu kürzen (z.B. Diskussion entfernen), bevor es zurück ins Antragsdossier gelangt
      - [x] es können beliebig viele Protokollauszüge generiert werden => #3245
      - [x] die Protokollauszüge werden in der Sitzungs-Übersicht aufgelistet => #3245
        - [x] die Protokollauszüge werden beim entsprechenden Traktandum aufgelistet => #3245
      - [x] die Protokollauszüge werden im eingerichten Antrag aufgelistet
      - [x] nach Bearbeitung kann der Protokollführer den Protokollauszug an den Ursprungsantrag zurücksenden
        - [x] In Sitzungsansicht pro Protokollauszug Aktionen zum fertigstellen
          - [x] "an Antragsteller senden" oder "Antragsteller informieren"
          - [x] "Aufgabe erstellen"
        - [x] Protokollauszug im Dossier ersetzen?
        - [x] Mehrere Protokollauszüge in unterschiedliche Dossiers?
        - [x] Darstellung "workflow" eines Traktandums, separate Spalte mit Task-Like Status-Icon?
  - ~~Abschliessen eines Traktandums (bestehende Aktion):~~
    - ~~Neu kann nur noch Abgeschlossen werden, wenn der Protokollauszug generiert wurde~~
- [x] Freitext => #3336
  - [x] Antragsvorlage für "Freitext" im Traktandum auswählen
  - [x] In Sitzungsdossier speichern
  - [x] ~~Soll keine Beschlussnummer erhalten~~ => https://4teamwork.slack.com/archives/C6C9K99
  - [x] Word-Datei löschen wenn Freitext-Traktandum entfernt wird? (Im Moment bleibt sie im Sitzungs-Dossier)
  - [x] Protokollauszug für Ad-Hoc Traktanden?
- [x] Traktandenliste in Sitzungsdossier speichern => #3346
  - [x] Damit es manuell überarbeitet werden könnte
  - [x] Mit Option zum neugenerieren, überschreibt Änderungen
  - [x] Versioniert
- [x] Sitzungsansicht umgestalten => jone
  - Ziel: Übersichtlichere Darstellung
  - [x] Metadaten oben aufklappbar => #3298
  - [x] Links dafür als Navigation die verschiedenen Traktanden
  - [x] Beschlussnummer in Sitzungsübersicht
    - [x] Beschlussnummer rechts neben Aktionen darstellen. => #3312
    - [x] Spalte Nummer und Titel zusammenlegen zu "Traktandum" => #3307
  - [x] Sitzungsangaben
    - [x] Bei Metadaten einen "bearbeiten"-button, welcher dann das Sitzungsangaben-Formular anbietet
- [x] Variablen in Word-Dokumente
  - [x] Wie werden Beschlussnummern/... in die Dokumente eingefügt?
- [x] **Finalisierung**
  - [x] Im Test erhält die committee-gruppe die `Editor`-Rolle damit sie das Proposal-Dokument aus- und einchecken darf. Dies entspricht nicht den produktiven Setups. Dies kann korrigiert werden, wenn die Lawgiver-Workflows umgesetzt sind => #3125
  - [x] Bug: Proposaltemplates-Tab hat noch keine visual-search-view, aber eine Button => `No view registered for: tabbedview_view-proposaltemplates-gallery` ([slack](https://4teamwork.slack.com/archives/C6C9K99F1/p1502207317786092)) => #3251

## Offene Punkte:
- Wie wollen wir Abschnitte umsetzen? Word mit Shablon definieren?
- Hat der Antrag auch die Metadaten wie ein Dokument?
- Wie werden Beschlüsse ins Ursprungsdossier zurückgespielt? Der Automatismus des Protokollauszugs pro Antrag entfällt, bisher wurde dieser ins Dossier kopiert.
- Ist es sinnvoll die Dokument-Titel zu ergänzen: (Antragsdokument/Beschlussdokument/Ad-Hoc Traktandum, ...). Besser weglassen? Oder statische labels im UI?

## Fixture rewrite/extension candidates:

https://github.com/4teamwork/opengever.core/blob/3d800506ac094c27aacc34e2f35a7d9aef132c74/opengever/meeting/tests/test_excerpt.py#L19-L35

## Technisches 
- auto-flush while building the fixture to always have auto-increment ids? then remove where we've don that manually with `create_session().flush`.
- make membership traversable over committee, not directly over member, to be able to allow committee-admins to edit memberships.
- general question, who can edit members/memberships?
- refactor responsibilities (agenda_item/proposal(model)/proposal(plone)/submitted proposal (plone), especially watch out for encapsulation violations

**Comment by phgross** [comment]
Nur eine kleine Nachfrage: 
Du schreibst _Der Inhalt der Anträge wird nicht mehr schematisch Erfasst; das System kann die einzelnen Teile nicht mehr automatisch verarbeiten._ wie behandelt ihr die Anforderung das gewisse Protokollteile im Protokollauszug landen sollen (_Antrag_, _Beschluss_) aber gewisse Teile nicht (_Diskussion_ etc.)?

**Comment by jone** [comment]
@phgross gute Frage: Dies wird dann eben nicht mehr vom System gemacht.
Der Benutzer erstellt mit `Protokollauszug generieren` eine Kopie, aus der er dann die Diskussion entfernt und die dann ins Antragsdossier zurück gesendet wird.
Das heisst wir geben die Verantwortung für das an den Benutzer ab. Dafür hat der Benutzer mehr Freiheiten Inhaltlich im Word, da das System die Bedeutung des Inhalts nicht mehr kennen muss.

**Comment by phgross** [comment]
@jone Ok. Ist zwar für den Protokollier ein Mehraufwand aber wohl die sinnvollste Variante, da es vom System keine Einschränkungen gibt.

**Comment by jone** [comment]
@phabegger möchtest du noch deinen <img src="http://www.valentin-gastro.ch/out/pictures/generated/product/1/380_340_75/602079_h.jpg" height="50px" /> dazugeben?

**Comment by bbuehlmann** [comment]
Bisher haben wir das Generieren der Protokollauszüge automatisiert auf Kosten der Gestaltungsfreiheit.

Mit der Word Protokollierung werden die Protokollauszüge dann manuell erzeugt (Ich denke dass die Benutzer schon jetzt die Protokollauszüge häufig manuell nachbearbeitet haben, deshalb sehe ich dort eine gewisse Kompromissbereitschaft)

**Comment by jone** [comment]
Der ursprüngliche Plan war dass wir im `Proposal` (und `SubmittedProposal`) ein neues Blob-Field `file` einfügen um das Antragsdokument zu speichern. Dafür müssten dann die Proposal-Typen Bumblebee, Office-Connector und Checkout/Checkin unterstützen.

Einfacher scheint der Ansatz, die Antragsdatei einfach in einem normalen GEVER-Dokument innerhalb des Proposal-Objekts zu speichern. So müssen wir nichts umbauen.
Ich werde diese neuen Ansatz verfolgen und oben die Checkliste aktualisieren.

**Comment by bbuehlmann** [comment]
:+1:

**Comment by jone** [comment]
Wir haben den Ablauf des Protokollierens und das Erstellen der Protokollauszüge intern Fachlich und von aus UI-Sicht diskutiert. Ich habe oben die Änderungs-Übersicht entsprechend aktualisiert.

@phgross Es wäre flott wenn du allenfalls den Plan oben gelegentlich überfliegen könntest und intervenierst wenn dies problematische Änderungen enthält 😎

**Comment by phgross** [comment]
@jone hier mal meine Fragen/Feedback zum "neuen Plan":

- Ist beim Traktandieren nun geplant das Dokument zu kopieren oder nicht? 
Die Variante: `Kopieren und Antragsdokument in Papierkorb verschieben.`, könnte problematisch sein. Es ist nicht sichergestellt, dass der Antragssteller Zugriff auf das Sitzungdossier hat. So könnte es sein, das er sein Dokument gar nicht mehr findet ...

**Comment by jone** [comment]
@phgross merci für die Fragen. Hier meine Gedanken dazu:

> - Ist beim Traktandieren nun geplant das Dokument zu kopieren oder nicht? 
Die Variante: `Kopieren und Antragsdokument in Papierkorb verschieben.`, könnte problematisch sein. Es ist nicht sichergestellt, dass der Antragssteller Zugriff auf das Sitzungdossier hat. So könnte es sein, das er sein Dokument gar nicht mehr findet ...

- Dies betrifft nur den _eingereichten_ Antrag im Committee, nicht den Antrag im Antragsdossier.
- Wird ausgelöst durch den Protokollführer (Traktandieren), nicht durchd en Antragsteller. Der Antragsteller soll nie Zugriff auf das Beschlussdokument haben.
- Das Antragsdokument hängt am (eingereichten) Antrag, nicht im Sitzungsdossier. Das Beschlussdokument könnte zu diesem Zeitpunkt auch am eingerichten Antrag hängen und dann erst nach dem Sitzuungsabschluss in irgendeiner Form ins Sitzungsdossier gelangen.
- Das Beschlussdokument wird vor allem zum Protokollieren benötigt, es hat eher temporären Charakter.

> - Was ist der langfristige Plan bezüglich Sablon, wir haben dann ja "zwei Module" die Words generieren/modifizieren.

Langfristig wollen wir Sablon ablösen. Wir möchten eher mit normalen Vorlagen und python-docx arbeiten.
Kurzfristig brauchen wir Sablon allenfalls noch zum generieren von Inhaltsverzeichnissen und ähnlichem.

> - Wird die Traktandenliste nach wie vor mit Sablon generiert?

Im moment ja, aber auch das möchten wir langfristig ablösen. Allenfalls noch nicht wichtig für den Durchstich.

> - Es ist demnach nach wie vor möglich Traktanden einzeln abzuschliessen, das Gesamtprotokoll wird erst beim Abschluss der Sitzung generiert? Das beisst sich in Meinen Augen mit der Einschränkung das Protokollauszüge erst nach dem Abschluss der Sitzung generiert werden können.

Bin mir nicht sicher ob ich deine Bedenken richtig verstehe.
Inputs:
- Das Antragsdokument wird beim traktandieren zum Beschlussdokument kopiert.
- Protokolliert wird im Beschlussdokument, dies umfangreich (inkl. Diskussion).
- Die Traktanden werden einzeln (?) beschlossen.
- Erst wenn alle Traktanden beschlossen sind (=Beschlussdokument ändert nicht mehr) kann das Gesamtprotokoll generiert werden.
- Das Gesamtprotokoll enthält alle Beschlussdokumente dieser Sitzung.
  - Möglicherweise können mehrere Gesamtprotokolle generiert werden? Wieso auch nicht?
- Generieren des "Protokollauszuges" ist pro Traktandum:
  - Ein Protokollauszug ist einfach eine Kopie des Beschlussdokuments.
  - Es können beliebig viele Protokollauszüge generiert werden (z.B. wenn unterschiedliche Parteien zu benachrichtigen sind).
  - Der Protokollauszug wird im Sitzungsdossier erstellt.
  - Eine Kopie des Protokollauszuges wird vom Sitzungsdossier verschickt (wichtig: nur letzte Version)

> - sind da die Buttons pro Traktandum gemeint? 
>  -  > Aktionen u.U. umbauen zu einem Menu, mit beschrifteten Aktionen

Ja genau. Ich werde die Gestaltung laufend anpassen.

> - Manuelle Erstellung des Auszugs finde ich gut, gibt es hierzu bereits Vorstellungen wie wir das im UI lösen?

Ich stelle mir eine Traktandum-Aktion in der Sitzungsansicht vor.

**Comment by deiferni** [comment]
alles weitere in https://github.com/4teamwork/gever/projects/1

**Comment by jone** [comment]
We have 🚢 ed.

**Comment by deiferni** [comment]
:shipit: 🎉
