### ISSUE TITLE
Meine Ablage: Löschen von Privatem Inhalt erlauben.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3569]
OGIP 19 (https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-1892/document-18937) Kapitel `4.2 Löschen von Dokumenten und Dossiers`

Todos:
 - Delete objects für die Role `Owner` in den Workflows PrivateFolders und PrivateDossiers
 - Aktionen sowohl in Detailansicht wie in Auflistungen (Tabbedview-action)
 - Delete confirmation view
 - Aktion selber

Note: Bitte prüfen ob eine eigene Aktion nötig ist oder ob nicht die Plone Aktion `Löschen` verwendet werden kann.

**Comment by tarnap** [comment]
# TODO

## Tabbedview

- [ ] Display the action in the overview
![dossier_overview_private_folder](https://user-images.githubusercontent.com/194114/32595500-7256b340-c530-11e7-9c29-45c3e5d17e17.png)


- [ ] Display the action in the document overview of a dossier
![document_overview_private_dossier](https://user-images.githubusercontent.com/194114/32595499-72339504-c530-11e7-9eb1-20837c874d58.png)


- [ ] Display the action in the subdossier overview of a dossier
![subdossier_overview_private_dossier](https://user-images.githubusercontent.com/194114/32595501-727352c0-c530-11e7-947c-8d6301e74bbd.png)


## Dossier

- [ ] Display the action in the dossier view
![dossier_view_private_folder](https://user-images.githubusercontent.com/194114/32595827-ab388552-c531-11e7-8158-8d76b167fe6f.png)


## Document

- [ ] Display the action in the document view
![document_view_private_folder](https://user-images.githubusercontent.com/194114/32595831-af4339a8-c531-11e7-91cc-c2d45a40e829.png)

**Comment by tarnap** [comment]
Added for the folder
![folder](https://user-images.githubusercontent.com/194114/32616083-c20e78a0-c571-11e7-8a5b-f9a82039bb48.png)

Added for the dossier / subdossiers
![subdossiers](https://user-images.githubusercontent.com/194114/32616084-c22db6a2-c571-11e7-89bb-8326dac1dcc8.png)

Added for the documents
![documents](https://user-images.githubusercontent.com/194114/32616075-be640a1c-c571-11e7-987e-e6c8e808f442.png)

**Comment by tarnap** [comment]
![loschen in personlicher ablage](https://user-images.githubusercontent.com/194114/32714157-d4d4b502-c84c-11e7-94f4-1fa8c50029dd.gif)
