### ISSUE TITLE
OGIP 17: Workflows for workspace family

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3679]
### Principles and thoughts:
- The new workflows are built with `ftw.lawgiver`.
- We use different roles than the regular dossier workflows: the principle is that a workspace is closed by default (participants must be authorized first), whereas a dossier is open by default.

### Document workflow:
- We are using the standard document FTI, which has a dossier-optimized workflow.
- We can either use our own workflow (apply it with a placeful workflow policy) or extend the document workflow to support both in the same workflow.
- For now, we try to keep the same document workflow; this means
  - avoid placeful workflow policy for, as it complicates things
  - use non-conflicting role names in the workspace area
  - maybe rewrite the document workflow with lawgiver at some point

### New workflows:
- `opengever_workspace_root` -> `opengever.workspace.root` #3675
- `opengever_workspace` -> `opengever.workspace.workspace` #3676
- `opengever_workspace_folder` -> `opengever.workspace.folder` #3677

### Roles:
on workspaces root:
- `WorkspacesUser` (Teamräume Benutzer): makes the workspace root visible; allowing to activate the feature only for a certain group
- `WorkspacesCreator` (Teamräume Ersteller): is allowed to create new workspaces.
  - (base on `WorkspacesUser`)

on each workspace:
- `WorkspaceOwner` [1] (Federführung): `WorkspaceAdmin` + manage workspace (edit; close)
  - (base on `WorkspaceAdmin`)
- `WorkspaceAdmin` (Admin): `Contributor` + manage contributors
  - (base on `WorkspaceMember`)
- `WorkspaceMember` (Teammitglied): CRUD on workspace content
  - (base on `WorkspaceGuest`)
- `WorkspaceGuest` (Gast): read workspace content
- these roles base on each other, so that a user only has one of those 4 roles at a given time on a given context.

on folders:
- block inheriting roles so that a folder can be protected
- `WorkspaceOwner` and `WorkspaceAdmin` should probably always have access, I guess
- therefore configurable roles:
  - `WorkspaceMember`
  - `WorkspaceGuest`

### Questions:
- Which admin roles should have acces to the contents of the workspaces? (`Site Administrator`)

[1] We are not using the `Owner` role, so that we can grant permissions on workspace content to the workspace owner. This is not that easy possible with Plone's standard `Owner` role as it is treated specially.

### Todos

- [x] Extend the users in the fixture as necessary.
- [x] Make sure that the workspace in the fixture is created as a normal user, not an admin.
- [x] Update existing tests so that we use a regular user, not an admin.

**Comment by jone** [comment]
Implemented with #3827
