### ISSUE TITLE
OGIP 32: switch repository favorites to new implementation

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#4105]
Since we implement a new generic favorites system, we want the existing repository favorites to also work together with the new system and use the same storage.

- [x] let the portlet use the new `@list-repository-favorites` REST API endpint for getting the user's favorites (#4102)
- [x] make the existing portlet JS use the new `@toggle-favorite`REST API endpoint for toggling favorites (#4102)
- [x] migrate [existing favorites](https://github.com/4teamwork/opengever.core/blob/026471b04ac1b4a1b68275283ad823e40ea36204/opengever/portlets/tree/favorites.py#L35) to the new SQL store (#4100)
- [x] reimplement caching of repository favorites
  - use last max(last modified) of the current user's favorites as cache key
  - put the cache key in the DOM and only load the favorites when the cache key changes
    - maybe use HTTP caching headers
  - when the cachekey is in the DOM, the [etag value](https://github.com/4teamwork/opengever.core/blob/026471b04ac1b4a1b68275283ad823e40ea36204/opengever/portlets/tree/favorites.py#L135) must be kept / adapted, otherwise it can be removed
- [x] remove the new longer used favorites  [storage](https://github.com/4teamwork/opengever.core/blob/026471b04ac1b4a1b68275283ad823e40ea36204/opengever/portlets/tree/favorites.py#L35) and [view](https://github.com/4teamwork/opengever.core/blob/026471b04ac1b4a1b68275283ad823e40ea36204/opengever/portlets/tree/favorites.py#L72) code
- [x] make sure that using the favorites-toggle in the title (#4103) also reloads the favorites portlet
- [x] review python and JS code of the repository favorites feature and remove everything which is not needed anymore

_harvest: `Feature: Favoriten (OGIP 32)`_

**Comment by phgross** [comment]
@elioschmutz yes that make sense.

By the way the favorites feature is enabled everywhere.
