### ISSUE TITLE
Erinnerung bei Fristablauf

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4205]
**Spezifikation**
Dem Benutzer insbesondere dem Auftragnehmer soll ermöglicht werden beim Akzeptieren der Aufgabe oder zu einem späteren Zeitpunkt, zu definieren wie er an die Aufgabe erinnert werden soll.

Dabei sollen die folgenden Optionen zur Verfügung stehen:
 - Keine
 - Am Morgen des Fristendes
 - Eine Tag vor Fristende
 - Eine Woche vor Fristende
 - Zu Beginn der Woche vom Fristende

Ein Setup-Handler, ähnlich wie dies bereits für den Versand der Daily Digest implementiert wurde, soll die entsprechenden Notifications erstellen.  Über welche Kanäle der Benutzer an Aufgaben erinnert werden will, kann der Benutzer in den Einstellungen des Benachrichtigungssystems selbst entscheiden. Auch sind der Versand von Digests, Mails und Erstellung von Glocken-Einträgen Sache des Benachrichtigungssystems.

Die ReminderSettings sollen auf dem Objekt (in den Annotations) gespeichert werden, zusätzlich aber auch im Globalindex indexiert werden. Folgendes Datenmodel ist vorgesehen:

ReminderSettings:
 - id 
 - task_id (task foreign_key)
 - option
 - remind_day
 - actorid
 - created

Eine Erinnerung soll einerseits beim Akzeptieren Formular definiert werden können, oder zu einem späteren Zeitpunkt auf der Detailansicht einer Aufgabe.

**Todos:**
Storage
 - [x] Annotation Storage für die ReminderSettings (PR: https://github.com/4teamwork/opengever.core/pull/4622 )
 - [x] SQL Model ReminderSettings erstellen (PR: https://github.com/4teamwork/opengever.core/pull/4619 )
 - [x] Task Synchronisation um ReminderSettings erweitern (Nachtrag: Synchronisation ist nicht notwendig. Es ist nicht möglich, für andere Benutzer eine Erinnerung zu setzten und auf dem Objekt werden keine Informationen über das Erinnerungsdatum gespeichert)

UI:
 - [x] Akzeptieren-Formulare um zusätzliches Feld erweitern. (PR: https://github.com/4teamwork/opengever.core/pull/4937)
 - [x] Erinnerungen in der Detailansicht darstellen, inkl. Option für die Erfassung eines ReminderSettings (PR: https://github.com/4teamwork/opengever.core/pull/4937)

Benachrichtigungssystem:
- [x] Erweitern der NotificationDefaults, so dass die Aufgaben-Erinnerung auch eingestellt werden kann (PR: https://github.com/4teamwork/opengever.core/pull/4609).
- [x] Activity-Objekt erstellen (PR: https://github.com/4teamwork/opengever.core/pull/4620 )
- [x] Setup handler für die tägliche Generierung der Notifications anhand der ReminderSettings (PR: https://github.com/4teamwork/opengever.core/pull/4736)
- [x] Keine Benachrichtigung erstellen wenn Task in Status "Ereledigt" (PR: https://github.com/4teamwork/opengever.core/pull/4931)

Event-Handling:
- [x] Automatische Aktualisierung vom `remind_day` bei Frist Veränderungen (PR: https://github.com/4teamwork/opengever.core/pull/4709)
- [x] Entfernen des ReminderSettings vom früheren Auftragnehmer beim neu zuweisen einer Aufgabe (PR: https://github.com/4teamwork/opengever.core/pull/4710)

REST-API:
- [x] Hinzufügen einer Erinnerung (PR: https://github.com/4teamwork/opengever.core/pull/4930)
- [x] Entfernen einer Erinnerung (PR: https://github.com/4teamwork/opengever.core/pull/4930)

**Comment by elioschmutz** [comment]
@phgross ich habe zu diesem Issues folgende Fragen:

- Der Auftragnehmer kann die Erinnerung beim Akzeptieren oder in der Detailansicht der Aufgabe definieren. Was sieht ein Benutzer, welcher nicht der Auftragnehmer ist? Soll er dieses Formular oder die Einstellung auf der Detailansicht trotzdem sehen => `Erinnerungen in der Detailansicht darstellen, inkl. Option für die Erfassung eines ReminderSettings`
- Warum soll der Wert redundant abgespeichert werden (Annotations und SQL)? Reicht nicht SQL aus? Oder geht es dabei um den einfacheren Zugriff auf die Option wenn man das Objekt hat?

Ansonsten sollte alles klar sein 👍

**Comment by phgross** [comment]
> Der Auftragnehmer kann die Erinnerung [...]

Nein ich würde hier keine Einschränkung vornehmen. Grundsätzlich soll jeder User eine Erinnerung bei einer Aufgabe erfassen können, egal ob er Auftragnehmer ist oder nicht. So können wir z.B. auch den Use Case abdecken, das eine Vorgesetzter die Bearbeitung einer Aufgabe "überwachen will". Aus technischer Sicht gibt es m.E. auch keine Gründe, die dies verunmöglichen würde. Es sollen natürlich nur die Erinnerungen des aktuellen Benutzers dargestellt werden. Siehe auch die Antwort zur zweiten Frage, es ist durchaus möglich das mehrere Erinnerungs-Optionen pro Aufgabe erfasst werden.

> Sind die Benachrichtigungsoptionen Benutzerspezifisch? Oder gilt [...]

Ja die Erinnerung soll benutzerspezifisch sein. Ob ein Benutzer über eine Aufgabe benachrichtigt werden will oder nicht, soll er selbst entscheiden können (deshalb auch das Attribut `actorid`)

> Warum soll der Wert redundant abgespeichert werden (Annotations und SQL)? Reicht nicht SQL aus? Oder geht es dabei um den einfacheren Zugriff auf die Option wenn man das Objekt hat?

Nur so ist es möglich, ein zentrale Generierung der Notifications zu implementieren. In einem Multi-Adminunit Deployment, soll das Script für die Generierung nur bei einer AdminUnit ausgeführt werden, dies soll aber die Erinnerung für alle Aufgaben (aller Mandanten) auslösen. Denn nur so können Successor-Predecessor Paare richtig behandelt werden (ähnlich wie beim Daily-Digest siehe https://intern.onegovgever.ch/operations/allgemein/#daily-digest)

**Comment by elioschmutz** [comment]
@phgross Kurze Frage zum Naming und Speicherort von `ReminderSettings`:

Die Tabelle wird nicht Einstellungen für Erinnerungen, sondern die Erinnerung selbst beinhalten.
Zudem beschränkt sich die momentane Implementation lediglich auf Aufgaben.

Ich schlage deshalb vor, dass wir die Modelklasse von `ReminderSettings` nach `TaskReminder` umbenennen. Die Tabelle dann `task_reminders`.

Ist das für dich i.O.? Oder spricht etwas dagegen?

Für den Speicherort des Models. Ich habe vor, das Model unter `opengever.globalindex/model/task_reminder.py` abzulegen. Das Task-Model befindet sich bereits im globalindex-Modul. Siehst du das auch so? Oder wo siehst du die Model-Implementation?

**Comment by elioschmutz** [comment]
Per Telefon mit @phgross geklärt: Ist eine Fehlüberlegung von meiner Seite her.

Alles bleibt so, wie es ursprünglich angedacht war!

**Comment by elioschmutz** [comment]
@phgross wie stellst du dir das GUI für die Task-Ansicht vor?

So etwas?
<img width="752" alt="bildschirmfoto 2018-10-03 um 18 03 31" src="https://user-images.githubusercontent.com/557005/46423578-2b657c00-c737-11e8-8df8-3365407bd5a9.png">

Oder eher in der Attributliste?
<img width="536" alt="bildschirmfoto 2018-10-03 um 18 07 59" src="https://user-images.githubusercontent.com/557005/46423620-433d0000-c737-11e8-9dc3-309247664c54.png">

Das ändern des Attributs stelle ich mir ohne Seitenreload vor. Der Benutzer wählt über ein Dropdown (egal ob als Button oder in der Tabelle) die Erinnerung aus und sie wird über die REST-API gesetzt. Ist das so OK? Oder hast du dir etwas anderes vorgestellt?

**Comment by phgross** [comment]
@elioschmutz Buttons finde ich nicht so passend, die restlichen Buttons sind alles Statusänderungen, bei welchen ein Antwort Formular erscheint.

> Das Ändern des Attributs stelle ich mir ohne Seitenreload vor. Der Benutzer wählt über ein Dropdown (egal ob als Button oder in der Tabelle) die Erinnerung aus und sie wird über die REST-API gesetzt. Ist das so OK? Oder hast du dir etwas anderes vorgestellt?
Finde ich sinnvoll.

Es geht ja hier grundsätzlich um das Erledigungsdatum, deshalb würde ich diese zwei Werte in der gleichen Zelle darstellen oder zumindest gleich darunter.

**Comment by elioschmutz** [comment]
Wie sieht es mit sowas aus (Mockup)?

![screen2](https://user-images.githubusercontent.com/557005/46460388-17b02900-c7bc-11e8-904f-c29737f5763c.gif)

**Comment by phgross** [comment]
@elioschmutz finde ich gut simpel und verständlich 👍
