### ISSUE TITLE
@listing endpoint should allow params isSubdossier/isSubtask

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#5775]
Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`

When querying the @listing endpoint the new gever frontend needs to be able to pass in the parameters `isSubdossier=false` and `isSubtask=false` so we can get the listing for multiple hierarchy depths but only receive the main dossiers/tasks.

**Comment by njohner** [comment]
# Todos
- [x] Neuer Index `is_subtask` (catalog, solr): Index already existed in catalog. Added in solr.
- [x] Neuer Indexer registieren für Interface und ein Indexer für Aufgaben: Indexer already existed. No need for a default indexer, because the index does not have the same name as any attribute on the task, so that children of tasks will not find the field by acquisition
- [ ] Expose von `is_subdossier` und `is_subtask` im `@listing` endpoint

**Comment by njohner** [comment]
This is deployed on dev

**Comment by phgross** [comment]
Mit neuem Frontend getestet, i.O.
