### ISSUE TITLE
teamraum ToDo's and ToDo lists should be addable really fast and easy

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5790]
Harvest: `[3.2.2.5 / 27] Projekt - OGIP 34 ToDo's` - `Entwicklung`

**Stories:**
- I would like to add new ToDo lists with just two clicks. Click on "Add new ToDo list", enter Title, hit enter to add the List. The focus should remain on the emptied Title field, so can directly add the next list.
- I would like to be able to quick add new ToDo's to every list, or to no list. Title, Responsible and the DueDate should be there. 
POC frontend: 4teamwork/gever-ui#307

**Umsetzung / Konzept**
Mockup: https://drive.google.com/drive/u/0/folders/1yvBZYVEcQn5CkFAgsVJ-66Sl6Ok201AX

Todos: 
 - [ ] Layout/Styling for the todos tab 
 - [ ] Inline Adding of todos
 - [ ] Inline Adding und Editing von todolists

**Comment by phgross** [comment]
Im POC gibt es nun zwei Orte für Content hinzuzufügen, das finde ich seltsam und nicht benutzerfreundlich. Ich bespreche mich diesbezüglich noch mit Florin ab.

**Comment by maethu** [comment]
@phgross 
Ich habe das bereits auch it @elioschmutz besprochen. 
Primär sollen die Inhalte einfache und schnell hinzufügbar sein.
Dass ToDo's ebenfalls noch per + Symbol addable sind stört mich persönlich nicht, aber ich würde bevorzugen, wenn dies nicht möglich ist. Dies müsste aber sicher nicht im ersten Wurf erledigt werden. 

ToDo's / ToDo Liste nur per + Symbol machen keinen Sinn. Niemand möchte so mit ToDo's arbeiten. Auch die Userstories könnte man so nicht erfüllen.

**Comment by phgross** [comment]
@maethu Danke für das Feedback. Wir haben uns bewusst dazu entschieden das vorerst via + umzusetzen. um nicht unnötig Aufwände in UI zu stecken, welche wir dann wieder überarbeiten.

Die Ansicht der Todos, und auch die Formulare zum Hinzufügen/Bearbeiten soll durch Florin definiert werden. Deshalb wollte ich das wir das so simple wie möglich halten - und das einfachste ist wenn es genau gleich funktioniert wie sonst überall auch. 

Ich werde Florin damit beauftragen die Todo-Seite zu mockupen, sobald er zurück ist aus seinen Ferien.

**Comment by phgross** [comment]
Wurde m.E. mit https://github.com/4teamwork/gever-ui/issues/436 gelöst, sie auch Kommentar PM (https://github.com/4teamwork/gever-ui/issues/436#issuecomment-545792749).
