### ISSUE TITLE
teamraum ToDo: Edit view and Responses

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5792]
_Harvest: `[3.2.2.5 / 27] Projekt` - `OGIP 34 ToDo's`_

**Stories:**
- On a ToDo I would like to be able to add a text (plain text) to the ToDo
- I would like to be able to add new answers. Latest answer appears at the bottom. 

The detail view of a todo contains the following parts (Styling according to https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2555/document-23284):
 - A checkbox to resolve/reopen a todo  
 - The Title
 - The Description 
 - All answers (oldest at the the top)
 - Form to add an answer

 Adding references is not part of this issue.

Detailansicht Todo:
 - [ ] A checkbox to resolve/reopen a todo  
 - [ ] Display Title, Text, responsible und deadline
 - [ ] The Description 
 - [ ] Verlinken aus Übersicht
~- [ ] Display Parent aka. TodoList Title~ _nicht Teil des BPI / MVP_
**Pts: 3**

Bearbeitung eines Todo:
- [ ] Edit Button separt in Detailansicht aufnehmen bzw. Standard-GEVER Content-Header aufnehmen
- [ ] Edit Formular umsetzen
**3 pts**

Responses Backend:
- [ ] Base-Reponse Funktionalität implementieren (als Basis dient opengever.task.response)
 - API GET Serializer erweitern (evtl. @respones)
 - POST `workspace-424/@responses`
 - Die Aufgaben Responses werden noch nicht angepasst. 
- [ ] Validierung
**8 pts**

Responses Frontend:
- [ ] Formular Textfeld, Hinzufügen Button
- [ ] Auflistung der Antworten (vuetify timeline)
**3 pts**

**Tasks:**
- [x] text Feld zum Todo
- [ ] Detailansicht von Todos
- [ ] Antwort Support im Backend (API, Speicherung ...)
- [ ] Antwort Formular und Darstellung im Frontend.

**Comment by phgross** [comment]
Wurde im Planing in separate Issues unterteilt #5852, #5853, #5854, #5855.
