### ISSUE TITLE
teamraum: ToDo record changes like github

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5793]
**Stories:**
- On ToDos I would like to changes people have made to the ToDo. Like `Mathias Leimgruber has changed the title from XYZ to QWERTZ`. `ToDo closed by Mathias Leimgruber`, `ToDo reopened by Hugo Boss`. Also changes on other fields, but Text field. 
- The changes should appear in order (latest at the bottom) and mixed with the comments. 

Hinweise:
 - Text Änderungen werden nicht historisiert

Tasks:
 - [x] BaseResponse Implemantation um `changes` erweitern.
 - [x] API
 - [ ] ~Event-Subscriber (Attributes / ObjectModifiedEvent)~
  > Nachtrag @elioschmutz : Das funktioniert nicht. Wir werden nie das Objekt vorher/nachher erhalten. Gem. Slack-Diskussion mit @phgross überschreiben wir den `PATCH` endpoint für `todos` damit wir die changes tracken können.
 - [x] Changes im Frontend darstellen

Harvest: https://4teamwork.harvestapp.com/projects/16507031

**Comment by phgross** [comment]
@maethu noch ein paar Unklarheiten hierzu:

- Es wären demnach vorerst Änderungen an den Metadaten Titel, Responsible, Deadline und Completed?

Wir stellen uns die Darstellung in einer Art Timeline vor, dabei wäre der Actor als Avatar ersichtlich). Das gäbe dann folgende Text Vorschläge, so ok?
 - Title von Anpassungen in der Policy prüfen zu Anpassungen in der Konfigurationsdatei prüfen verändert. 
 - Geschlossen.
 - Wieder eröffnet
 - Neu an Peter Meier zugewiesen (ehemals Fritz Müller)
 - Frist zum 23.2.2020 verändert (ehemals 01.01.2020)

**Comment by maethu** [comment]
> Es wären demnach vorerst Änderungen an den Metadaten Titel, Responsible, Deadline und Completed?

Das würde für mich passen. 

Allenfalls käme hier noch das verschieben in eine (neue / andere) Liste hinzu.

> Wir stellen uns die Darstellung in einer Art Timeline vor, dabei wäre der Actor als Avatar ersichtlich). Das gäbe dann folgende Text Vorschläge, so ok?

>  - Title von Anpassungen in der Policy prüfen zu Anpassungen in der Konfigurationsdatei 
prüfen-  verändert.
>- Geschlossen.
>- Wieder eröffnet
>- Neu an Peter Meier zugewiesen (ehemals Fritz Müller)
>- Frist zum 23.2.2020 verändert (ehemals 01.01.2020)

Ja finde ich so gut. 
Siehe auch https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2555/document-23284#overview Seite 9

Ich habe mich dabei vor allem an github orientiert. 
Es müsste sicher pro Eintrag noch ein Zeitstempel dargestellt werden, wann die Manipulation stattgefunden hat.
