### ISSUE TITLE
Backend work lightweight content type "ToDo"

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5802]
Harvest: `[3.2.2.5 / 27] Projekt - OGIP 34 ToDo's` - `Entwicklung`

Todos: 
- [x] Dexterity FTI (one state Workflow) (#5808)
  - Schema: Title, Text (Plain Text mit Zeilenumbrüchen), Responsible (Person), deadline, done
- [x] Workspace Vocabularies (ActualWorkspaceMembers, PotentialWorkspaceMembers)*  Implementierung verbessern (#5836)
- [x] Rest API* (#5808)
- [x] SearchableText prüfen oder ergänzen. (#5808)
- [x] Indexer* (#5808)
- [x] Hard limit für maximal 500 Anzahl* (#5836)
- [x] ID: `todo-${global-gever-counter}` --> `todo-2383` (#5836)
