### ISSUE TITLE
Frontend work: lightweight content type "ToDo"

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5803]
Harvest: `[3.2.2.5 / 27] Projekt - OGIP 34 ToDo's` - `Entwicklung`

Frontend:
- [x] Auflistung aller Todos 
  - [x] Listing Endpoint ergänzen um ein zusätzlichen `mode`
  - [x] Batch Size auf 500
- [x] Add Form
- [x] Toggler für Done Flag

Abgrenzung:
 - [x] Keine edit View
 - [x] Text wird nicht dargestellt

Todos (23. Juli 2019):
 - [x] Hinzufügen vereinheitlichen
