### ISSUE TITLE
ToDo's should be organized in lists: Frontend

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5826]
Details see #5789

Nachgeladen für Sprint #2

- [x] Auflistung der Todos anpassen, so dass sie die Todos verschachtelt (nach todolist) darstellt
- [x] Erstellen und bearbeiten (inline editing) von Todolist
- [x] Move von Todolist via DnD
- [x] Move von Todos in eine Todolist 
- [x] Löschen von Todolist

Update:
 - WIP Branch: `todolist_frontend`
 - Für den Drag'n Drop Support kann die Library vuedraggable verwendet werden, ist auch bereits im RIS im Einsatz.
