### ISSUE TITLE
Detailansicht für Todos gemäss Mokups umsetzten.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6048]
![Bildschirmfoto 2019-11-12 um 13.21.03.png](https://images.zenhubusercontent.com/556c175e4f7a08fbb7f30b66/3a4d9ee3-b49a-4e0d-9e80-defa9d16fa9d)

- Detailansicht soll über die Aufistung von rechts dargestellt werden
- Navigation zwischen den Todos nach wie vor möglich
- Der Aufgabenverlauf - aber eigentlich die ganze Darstellung, soll stark von der Detailansicht von Aufgaben abgeleitet werden.

**Comment by elioschmutz** [comment]
# Current state

## PRs
☑️ PR https://github.com/4teamwork/gever-ui/pull/747: Refactoring Task Responses
☑️ PR https://github.com/4teamwork/gever-ui/pull/750: Implement Todo Detail view

## Todos
- [ ] Inline-Editing
  - [ ] Refactoring Task metadata card items to make it reusable
- [ ] Handle URL to Todos (currently, a todo has no direct url)
- [ ] Remove unused `Todo.vue` component

**Comment by elioschmutz** [comment]
Updated estimate from 5 to 8 as discussed on the daily of the 21.11.2019.

**Comment by elioschmutz** [comment]
# Ziel
Ein Benutzer soll eine direkte URL zu einem Todo erhalten. 

# Problem unique Todo URL
Grundsätzlich besitzt jede GEVER-Ressource eine eigene URL. Wird also die URL https://gever.ch/workspaces/workspace-1/todo-1 aufgerufen, müsste die Detailansicht vom Todo-1 angezeigt werden.

Leider ist dies mit den aktuellen UX-Spez nicht oder nur sehr schwer umzusetzen.

Die Designvorlage sieht vor, dass wir uns immer im Kontext vom Workspace befinden. 
Wenn der Benutzer auf ein Todo klickt, soll von rechts eine Detailansicht eingeblendet werden mit den Todo-Details und diverse Bearbeitungs- und Kommentarfunktionen für den Todo. Der Kontext bleibt jedoch der Workspace. D.h. die Breadcrumbs, das Hinzufügen-Menu, Bearbeiten-Menu oder die Tabs Übersicht, Dokumente oder Todo sind immer sichtbar und beziehen sich immer auf den Workspace selbst.

# Wichtige Informationen zur aktuellen Umsetzung
PR: https://github.com/4teamwork/gever-ui/pull/750

Der Arbeitsraum lädt immer alle Todos und Todolisten beim öffnen des Todo-Tabs. Wenn im State `selectedTodoUid` eine UID angegeben ist, wird die entsprechende Detailansicht des Todos angezeigt.

# Lösungsvorschläge
## V1 - Hashtag
### URL Vorschlag
https://gever.ch/workspaces/workspace-1#UID

### Umsetzung
Beim Klick auf ein Todo-Item wird die `selectedTodoUid` gesetzt und die Detailansicht entsprechend geöffnet.

Zusätzlich wird die URL mit einem Hashtag und der UID des selektierten Todo-Items erweitert.

Beim Seitenreload wird der Hash-Value als `selectedTodoUid` initial verwendet.

### Argumentation
Wir verlassen den Arbeitsplatz nicht. Der Kontext bleibt weiterhin der Workspace. Deshalb sollte die URL auch nicht ändern.

Technisch sollte der Haupt-Kontext auch nicht ändern, weil wir uns weiterhin auf dem Arbeitsplatz befinden und sich alle Aktionen usw. auf den Arbeitsplatz beziehen.

Üblicherweise wird mit einem Hash eine Untereinheit einer Ressource adressiert. Im weitesten Sinne ist die Anzeige der Detailansicht auch eine Untereinheit der Todo-Auflistung und somit semantisch auch korrekt.

@4teamwork/gever bitte fügt bei Bedarf eigene Varianten hinzu (z.b. eigene URL für Todos) oder kommentiert die bestehenden. Ich sehe momentan nur den Weg mit dem Hash als sinnvoll. Deshalb unterlasse ich die Ausarbeitung von weiteren Varianten aus Zeitgründen.

**Comment by lukasgraf** [comment]
@elioschmutz D.h. über die REST API würde man ein Todo ebenfalls über `https://example.org/workspaces/workspace-1#UID` ansprechen? Also z.B. um ein Todo zu löschen z.B. ein `DELETE` Request auf diese URL?

**Comment by elioschmutz** [comment]
@lukasgraf nein, für API-Request werden die richtigen URLs verwendet: https://example.org/workspaces/workspace-1/todo-1.

**Comment by lukasgraf** [comment]
Sorry, ich dachte es sei ziemlich offensichtlich dass dies eine rhetorische Frage ist - um aufzuzeigen, dass eine URL mit einem Hashtag inkonsistent ist mit den Resourcen, die wir bereits haben. 

_(**Wenn** über die API ein `DELETE https://example.org/workspaces/workspace-1#UID` gemacht würde, würde natürlich der komplette Workspace gelöscht)_

Das Mockup für das User-Interface mag eine bestimmte Darstellungsweise vorschlagen, aber aus Sicht von HTTP Resourcen ist für mich der Fall klar - workspaces, todo lists und todos sind völlig separate Resourcen. Sie können separat erstellt, mutiert/gelöscht und addressiert werden, und wir haben ja auch eigene Plone-Inhaltstypen dafür verwendet.

Überall sonst gilt in `plone.restapi` das Prinzip der HTTP Content-Negotiation: Die URLs sind die echten URLs von Plone-Objekten, und der Request im Webbrowser der HTML ausliefert unterscheidet sich nur von einem API request durch den `Accept` Header: `text/html` vs. `application/json`. Anders gesagt: Man kann für jedes Objekt die URL oben aus der Addresszeile des Browsers kopieren, und darauf einen API request machen indem man `Accept: application/json` setzt. Dieses Prinzip würde durch solche Hashtag-URLs völlig verletzt.

Aus diesem Grund erscheint mir die Argumentation auch ziemlich "reverse engineered" - _"Im weitesten Sinne ist die Anzeige der Detailansicht auch eine Untereinheit der Todo-Auflistung und somit semantisch auch korrekt."_ ist IMHO sehr weit hergeholt.

Es scheint mir auch, dass der Begriff des Kontext ziemlich überladen ist. Aus Plone/Zope Sicht ist der Fall klar - der Kontext (das Objekt das published wird) ist das Todo. Der Kontext im Sinn von "Zusammenhang" oder "Rahmen" im User-Interface mag der Workspace sein. Und dann gibt es den `context` in der GEVER UI Vue app, der anscheinend aus irgend einem Grund der Workspace ist, auch wenn es um Ansichten von anderen Objekttypen geht.

Ich sehe zur Zeit aber wirklich die technische Notwendigkeit nicht, dass das so ist, und es erscheint mir sogar ziemlich falsch. Es ist überhaupt nichts aussergewöhnliches, dass im User-Interface Elemente um den primären Content herum von anderen Objekten kommt:

Die Breadcrumbs auf einer Dossier-Ansicht kommen genau so vom umgebenden Kontext (rauf bis zur Plone-Seite). Und das Ordnungssystem ist ebenfalls nicht Teil eines Dossiers, sondern umgebender Rahmen-Kontext. Trotzdem würden wir nie die Views auf dem `repositoryfolder` Typ registrieren, und URLs wie `ordnungssystem#dossier-17` verwenden.

Zur Zeit ist, so wie ich das verstanden habe, die View auf dem Workspace, und holt sich noch zusätzliche Informationen zu Children - Todolisten, und ggf. Details zum darzustellenden Todo. Warum kann nicht stattdessen die View auf dem Todo sein, und sich die nötigen Informationen zu den Parents holen?

**Comment by all4manu** [comment]
Beide Argumentationen haben valide Punkte. Damit wir alle vom Gleichen sprechen, erkläre ich noch kurz - in etwas vereinfachter Form - wie unsere Vue Frontend App z.Z. funktioniert:

Der Ablauf bis ein HTML Template gerendert wird, ist immer gleich:

1. User gibt URL ein oder klickt auf einen Link in der App
2. Anhand der URL wird via API der "Kontext" geholt. "Kontext" hier bezeichnet einfach den Inhalt, den wir über ein GET Request mit der entsprechenden URL erhalten.
3. Über den Kontext bzw. den GET Request erhalten wir den Portal-Type für die angefragte Ressource.
4. Sobald wir den Portal-Type kennen, können wir die korrekte Vue Komponente laden.

Damit dieser Ablauf funktioniert, haben wir in unserer gesamten Vue App nur eine Route definiert. Hinter dieser Route befindet sich "globale" Vue Komponente, welche den oben beschriebenen Ablauf durchläuft und dann die Komponenten rendert.

Diese Architektur ist zwar nicht grundsätzlich falsch, aber entspricht nicht zu 100% der Idee von Vue. Gemäss Vue müsste man in unserer App mehrere Routen definieren und dann pro Route die richtige Komponente für das HTML Template hinterlegen. Dadurch wäre es einfacher den von @lukasgraf beschriebenen Forderungen (URLs der App sollen analog sein wie auf der API) gerecht zu werden.

Ich war nicht dabei als man sich entschieden hat die Routen so zu bauen wie sie jetzt sind. Ich nehme an es gab wichtige Gründe dafür - und ich würde im Moment auch nichts dran ändern, denn eine solche Änderung würde so ziemlich der ganze Aufbau der App betreffen. Am besten kann uns @buchi die Überlegungen, welche ins Routing eingeflossen sind erklären und falls wir diese Architektur hinterfragen, müssten wir ihn ins Boot holen.

Aus meiner Sicht lässt sich das Problem auf eine Frage der Priorität reduzieren. Was ist wichtiger:

1. Erreichbarkeit der ToDo Details über die URL
2. Das Design - sprich, dass sowohl der Teamraum wie auch die Detailansicht gleichzeitig sichtbar sind

So wie die App z.Z. aufgebaut ist, können wir nur eine der beiden Anforderungen erfüllen. Sobald wir versuchen beides zu erfüllen, müssen wir entweder damit leben, dass wir dem RESTful Prinzip nicht mehr entsprechen oder wir müssen die Architektur der App hinterfragen.

**Comment by elioschmutz** [comment]
Wie am Daily besprochen, wird nun die neue Detail-Ansicht für das Todo verwendet. Beim klicken auf ein Todo-Item wird man wie bisher auf ein Todo weitergeleitet.

![screen2](https://user-images.githubusercontent.com/557005/69649945-1c920500-106e-11ea-9fa3-29ff4cfb91d6.gif)

Was ist nun aber das Ziel? Verfolgen wir weiterhin das Ziel, die Todo-Ansicht gem. Mockups umzusetzen? Oder ist dies nun vom Tisch? Der PR https://github.com/4teamwork/gever-ui/pull/750 setzte bereits alles gem. UX-Spez um und war bereit zum Mergen. Ich habe nun die Detailansicht für die bestehende Todo-Ansicht verwendet. Der Slide-In der Detailansicht habe ich ersetzt mit einem laden des Todos selbst. Somit hat ein Todo wieder eine eigene URL.

Dies alles mit dem Hintergrund, dass wir das UX gem. Mockups umsetzten werden. D.h. Komponenten, Tests und Funktionen, welche für die Umsetzung gem. Mockup notwendig waren, werde ich nicht löschen. Die Umsetzung des UIs war mit viel Aufwand verbunden. Nun alles zu löschen, um später wieder alles neu zu implementieren finde ich nicht so toll.

@phgross @lukasgraf @all4manu Welches Ziel verfolgen wir nun also für diesen Issue?

**Comment by elioschmutz** [comment]
Ich habe die bisherige Implementation komplett entfernt und neu umgesetzt. 

Hier gibt es ein Backup von der alten Implementation: https://github.com/4teamwork/gever-ui/tree/es-6048-todo-detail-view-backup

Der PR https://github.com/4teamwork/gever-ui/pull/750 ist soweit bereit für das Review.

**Comment by all4manu** [comment]
@phgross @elioschmutz @lukasgraf Ich habe den Stand vom PR mal gemerged. Ich schlage vor, dass wir einen neuen Issue für die Implementation gemäss UX-Spez machen. Von der Umsetzung würde ich ZenHub als Beispiel nehmen. Dort ist es folgendermassen gelöst:

- Klickt man im ZenHub auf einen Issue, so wird dieser im Overlay dargestellt aber die URL in der Adresszeile ist diejenige vom Issue (ganz "normal" und ohne Hash)
- D.h. wenn man die Adresse kopieren und in einem neuen Fenster einfügen würde, so würde der Issue "Fullscreen" dargestellt

In diesem Sinn braucht es beide Ansichten. Das Overlay und die "Fullscreen" Ansicht. D.h. der Aufwand von dir Elio war nicht umsonst. Eigentlich müssen wir nur noch einen Weg finden, die URL zu ändern wenn man im Workspace auf ein ToDo klickt und das Overlay eingeblendet wird.

**Comment by phgross** [comment]
Fachliches Review 👍
