### ISSUE TITLE
Dokumente übertragen (Frontend)

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6198]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

Gesplittet von #6156 in Backend und Frontend

_**Nur FRONTEND in diesem Issue**_

PBI ist Teil des [OGIP 63 - Schnittstelle Teamraum und OneGov GEVER](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023) 

User Stories 
> * Als Sachbearbeiterin Sachbearbeiter/In möchte ich einzelne Dokumente in den Teamraum transferieren können, damit ich diese Dritten zur Verfügung stellen und evtl. mit ihnen weiterbearbeiten kann.

Es soll möglich sein, GEVER Dokumente in den Teamraum zu übertragen. Dabei wird eine Kopie inkl. Meta-daten erstellt. Diese wird technisch nicht verlinkt, ein zurückführen von Änderungen als neue Version oder ähnliches ist deshalb nicht möglich. 
Es wird nur die aktuelle Version kopiert, frühere Versionen werden nicht übertragen. Sind aus-gewählte Dokumente zurzeit ausgecheckt wird der Benutzer darauf hingewiesen und die Über-tragung abgebrochen.

#### Klärung
- Die Aktion soll in einer Art und Weise umgesetzt werden, dass zuerst die Dokumente ausgewählt werden, die in einen Teamraum übertragen werden sollen, und dann die Aktion.
- Geschätzt wird eine serielle Erstellung der Dokumente durch das Frontend (7. Dokumente - 7 requests des Frontends an GEVER die proxied werden auf Teamraum).
- Aktion "Dokument in Teamraum übertragen" auch darstellen wenn noch gar kein verknüpfter Tearaum vorhanden? Entscheid: Aktion wird nicht dargestellt, solange nicht mindestens 1 Teamraum existiert (unter Berücksichtigung der Security).

#### Offene Fragen
- Wie wird dem User der Ziel-Teamraum (Auswahl der Destination) präsentiert?

**Comment by jone** [comment]
@all4manu könntest du diese Story aus Sicht Frontend ergänzen damit sie schätzbar ist? Merci!

**Comment by all4manu** [comment]
#### Das Frontend geht von folgenden Annahmen aus

- Das Backend sendet eine Action-ID auf Kontext-Ebene (z.B. `object`, `object_buttons', 'file_actions`) unter Berücksichtigung aller verlangten Bedingungen (Berechtigung, mind. 1 Teamraum verlinkt, etc.) => Wird benötigt um im Listing eine einzelne Datei zu übertragen.
- Das Backend sendet eine Action-ID auf Folder-Ebene (`folder_buttons`) ebenfalls unter Berücksichtigung aller verlangten Bedingungen => Wird benötigt um im Listing mehrere Datein zu markieren und alle zu übertragen.
- Es gibt einen Vocabulary Endpoint mit welchem man eine Liste der verlinkten Teamräume abrufen kann => Wird benötigt für den Dialog zur Auswahl des Ziel-Teamraums.
- Es gibt einen Enpoint, an welchen die `@id` der zu übertragenden Dateien geschickt werden kann.

#### Fragen

- Soll der Upload Fortschritt angezeigt werden, oder genügt es lediglich drei Stati anzuzeigen: Busy, Success, Error? Je nach antwort muss der Enpoint, welcher für den Upload benutzt wird anders implementiert sein.

#### ToDo

- [ ] Einblenden des Buttons pro Listing Element.
- [ ] Einblenden des Buttons wenn mehrere Listing Elemente ausgewählt sind.
- [ ] Erstellen der Action für die Übertragung von einer Datei.
- [ ] Erstellen der Action für die Übertragung von mehreren Dateien.
- [ ] Erstellen des Store moduls und der GUI Komponenten zur Anzeige vom Upload-Status.

**Comment by jone** [comment]
-> "Dokumente übertragen" aus Teamraum-Menu ausblenden

**Comment by jone** [comment]
✅ Funktioniert aus meiner Sicht auf dev.teamraum.ch wie erwünscht.
